apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==       
  DB_USER: cHJvamV0X3VzZXI=           
  DB_PASSWORD: dG9vcg==              
  DB_NAME: cHJvamV0azg=               
