apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: node-web-app
        image: maureeendr/node-web-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "projet_user"
        - name: DB_PASSWORD
          value: "toor"
        - name: DB_NAME
          value: "projetk8"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: web
